#server:
#  port: 7072
#spring:
#  application:
#    name: server-02
#    ##defaultZone 表示向自身注册
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:7070/eureka/
#      ##instanceId需要唯一,如果不配置,多个节点中只会有一个生效
#  instance:
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}